pipeline {
    agent any

    environment {
        AWS_REGION = "us-east-1"
        TF_DIR = "terraform"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/reshmanavale/Three-Tier-Application-Deployment-with-AWS-Terraform-and-Jenkins.git' // Replace with your Git repo
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Fetch EC2 IPs') {
            steps {
                script {
                    def tfOutput = sh(script: "cd ${TF_DIR} && terraform output -json", returnStdout: true).trim()
                    def output = readJSON text: tfOutput
                    env.FRONTEND_IP = output.web_public_ip.value
                    env.DB_IP = output.db_private_ip.value
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                sh """
                    scp -o StrictHostKeyChecking=no ${TF_DIR}/scripts/backend_setup.sh ubuntu@${FRONTEND_IP}:/home/ubuntu/
                    ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_IP} 'chmod +x backend_setup.sh && ./backend_setup.sh ${DB_IP}'
                """
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh """
                    scp -o StrictHostKeyChecking=no ${TF_DIR}/scripts/frontend_setup.sh ubuntu@${FRONTEND_IP}:/home/ubuntu/
                    ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_IP} 'chmod +x frontend_setup.sh && ./frontend_setup.sh ${FRONTEND_IP}'
                """
            }
        }
    }

    post {
        always {
            echo "Deployment finished"
        }
    }
}
