pipeline {
    agent any

    environment {
        AWS_REGION = "us-west-1"
        TF_DIR = "Terraform"
        FRONTEND_PUBLIC_IP = "13.52.163.0"   // Replace with actual public IP of frontend EC2
        BACKEND_PRIVATE_IP = "10.0.2.224"    // Replace with actual private IP of backend EC2
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/reshmanavale/Three-Tier-Application-Deployment-with-AWS-Terraform-and-Jenkins.git'
            }
        }

        stage('Terraform Init & Apply') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Deploy Backend (React App)') {
            steps {
                sh """
                    scp -o StrictHostKeyChecking=no ${TF_DIR}/scripts/backend_setup.sh ubuntu@${FRONTEND_PUBLIC_IP}:/home/ubuntu/
                    ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_PUBLIC_IP} 'chmod +x backend_setup.sh && ./backend_setup.sh'
                """
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh """
                    scp -o StrictHostKeyChecking=no ${TF_DIR}/scripts/frontend_setup.sh ubuntu@${FRONTEND_PUBLIC_IP}:/home/ubuntu/
                    ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_PUBLIC_IP} 'chmod +x frontend_setup.sh && ./frontend_setup.sh ${BACKEND_PRIVATE_IP}'
                """
            }
        }
    }

    post {
        always {
            echo "✅ Three-tier app deployment completed"
        }
    }
}
